spring:
  application:
    name: Sekhmet Api
amazon:
  aws:
    region:
  dynamodb:
    endpoint:
    table-name-prefix: ${application.env}
management:
  info:
    env:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
    defaults:
      enabled: true
    git:
      enabled: true
      mode: simple
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info"
info:
  application:
    name: ${spring.application.name}
    description: Sekhmet Api
    version: '@project.version@'
    build-time: '@timestamp@'

application:
  env:
  s3:
    region: 'eu-west-3'
    endpoint: 'http://localhost:4566'
    bucket: 'media-bucket'
  twilio:
    account-sid:
    auth-token:
    api-secret:
    api-sid:
    verify-sid:
    conversation-sid:
    channel-admin-sid:
    channel-user-sid:
