name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to destroy (Dev or Prod)'
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Set env vars and run script
        run: |
          env_upper=$(echo $env | tr '[:lower:]' '[:upper:]')
          echo "${{ secrets['TF_' + env + '_SET_ENV_VARS_SCRIPT'] }}" > set_env.sh
          chmod +x set_env.sh
          . ./set_env.sh
          echo "TF_VAR_application_version=nothing" >> $GITHUB_ENV
        env:
          env: ${{ github.event.inputs.env }}
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/${{ github.event.inputs.env }}


      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform/${{ github.event.inputs.env }}
